import './styles.css'

const COLORS={film:'#e7b86b',actor:'#8db6c7',director:'#d98169'}
const esc=(s)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const state={movies:[],nodes:[],edges:[],activeView:'graph',selected:null,focus:null,query:'',minYear:1970,maxYear:2024,path:[],pathAnimating:false,from:null,to:null}
const root=document.querySelector('#app')

async function init(){
  try { state.movies=await fetch('/data/movies.json').then(r=>r.json()) } catch(e){ state.movies=[] }
  buildGraph(); render();
}
function buildGraph(){
  const byId=new Map(); const nodes=[]; const edges=[]
  const add=(id,type,label,meta={})=>{if(!byId.has(id)){const n={id,type,label,...meta};byId.set(id,n);nodes.push(n)} return byId.get(id)}
  for(const m of state.movies){const movie=add('m:'+m.id,'film',m.title,{year:m.year,genre:m.genre,poster:m.poster,director:m.director}); const d=add('d:'+slug(m.director),'director',m.director); edges.push({source:movie.id,target:d.id,kind:'directed'}); for(const a of m.cast){const actor=add('a:'+slug(a),'actor',a); edges.push({source:movie.id,target:actor.id,kind:'acted'})}}
  state.nodes=nodes;state.edges=edges
}
function slug(v){return v.toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function filteredMovies(){return state.movies.filter(m=>m.year>=state.minYear&&m.year<=state.maxYear)}
function neighbors(id){const ids=new Set([id]); state.edges.forEach(e=>{if(e.source===id)ids.add(e.target);if(e.target===id)ids.add(e.source)});return ids}
function nodeDegree(id){return state.edges.filter(e=>e.source===id||e.target===id).length}
function nodeMeta(n){const ms=state.movies.filter(m=>n.type==='film'?'m:'+m.id===n.id:n.type==='director'?slug(m.director)===n.id.slice(2):m.cast.some(a=>'a:'+slug(a)===n.id)); return ms}
function render(){root.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">✦</span><span>CINEMA <i>ATLAS</i></span></div><div class="top-meta"><span class="live-dot"></span> ${state.movies.length} films mapped <span class="sep">/</span> 1970—2024</div></header><main class="layout"><aside class="sidebar"><div class="eyebrow">THE FILM UNIVERSE</div><h1>A map of<br/><em>cinema.</em></h1><p class="intro">Wander through the people and stories that shape the moving image.</p><div class="nav-tabs"><button class="tab ${state.activeView==='graph'?'active':''}" data-view="graph"><span>01</span> GRAPH</button><button class="tab ${state.activeView==='timeline'?'active':''}" data-view="timeline"><span>02</span> TIMELINE</button><button class="tab ${state.activeView==='degrees'?'active':''}" data-view="degrees"><span>03</span> SIX DEGREES</button></div><div class="legend"><div class="eyebrow">NODE TYPES</div><div><span class="dot film"></span> Films</div><div><span class="dot actor"></span> Actors</div><div><span class="dot director"></span> Directors</div></div><div class="sidebar-note"><span class="quote">“</span><p>Every film is a constellation. Follow one light and find another.</p></div></aside><section class="workspace">${state.activeView==='graph'?graphView():state.activeView==='timeline'?timelineView():degreesView()}</section></main><footer><span>Built with IMDb non-commercial datasets.</span><span>IMDb data © IMDb.com, Inc. Used for non-commercial purposes. <b>Explore with care.</b></span></footer></div>`; bind(); if(state.activeView==='graph')drawGraph()}
function graphView(){const shown=filteredMovies().length;return `<div class="view-head"><div><div class="eyebrow">01 / CONSTELLATION</div><h2>Find your way around.</h2></div><div class="view-stat"><strong>${shown}</strong><span>films in view</span></div></div><div class="control-row"><label class="search"><span>⌕</span><input id="search" value="${esc(state.query)}" placeholder="Search a film, actor, or director"/><kbd>⌘ K</kbd></label><button class="ghost" id="reset">RESET VIEW</button></div><div class="graph-wrap"><svg id="graph" role="img" aria-label="Interactive cinema knowledge graph"></svg><div class="graph-hint"><span>DRAG</span> to explore <span>·</span> <span>DOUBLE-CLICK</span> to expand</div>${state.selected?detailCard(state.selected):''}</div>`}
function detailCard(n){const ms=nodeMeta(n);return `<aside class="detail-card"><button class="close" id="close">×</button><div class="card-type" style="color:${COLORS[n.type]}">${n.type.toUpperCase()}</div><h3>${esc(n.label)}</h3>${n.type==='film'?`<div class="card-year">${n.year} <span>${esc(n.genre||'Drama')}</span></div>`:`<div class="card-year">${ms.length} film${ms.length===1?'':'s'} in atlas</div>`}<div class="card-films">${ms.slice(0,4).map(m=>`<div><span>${m.year}</span>${esc(m.title)}</div>`).join('')}</div><button class="focus-button" data-focus="${n.id}">FOCUS NEIGHBORHOOD →</button></aside>`}
function timelineView(){const ms=filteredMovies(); const years=[1970,1980,1990,2000,2010,2020];return `<div class="view-head"><div><div class="eyebrow">02 / TIME MACHINE</div><h2>Stories in sequence.</h2></div><div class="view-stat"><strong>${state.minYear}</strong><span>starting year</span></div></div><div class="timeline-controls"><div class="range-label"><span>1970</span><span class="range-current">${state.minYear} — ${state.maxYear}</span><span>2024</span></div><input id="year" type="range" min="1970" max="2024" value="${state.minYear}"/><div class="timeline-chips">${years.map(y=>`<button data-year="${y}" class="${state.minYear===y?'active':''}">${y}</button>`).join('')}</div></div><div class="timeline-grid">${ms.slice().sort((a,b)=>a.year-b.year).map(m=>`<article class="film-row" data-id="m:${m.id}"><div class="film-year">${m.year}</div><div class="film-line"></div><div class="film-info"><h3>${esc(m.title)}</h3><p>${esc(m.director)} <span>·</span> ${m.cast.slice(0,3).map(esc).join(' · ')}</p></div><div class="film-tag">${esc(m.genre||'FILM')}</div></article>`).join('')}</div>`}
function degreesView(){const people=state.nodes.filter(n=>n.type!=='film').sort((a,b)=>a.label.localeCompare(b.label));return `<div class="view-head"><div><div class="eyebrow">03 / CONNECTIONS</div><h2>Six degrees of cinema.</h2></div><div class="view-stat"><strong>${state.path.length||'—'}</strong><span>${state.path.length?'nodes in path':'shortest path'}</span></div></div><div class="degrees-intro">Choose two people. The atlas will trace the shortest route through the films they share.</div><div class="picker-grid"><label>START<select id="from"><option value="">Select a person</option>${people.map(n=>`<option value="${n.id}" ${state.from===n.id?'selected':''}>${esc(n.label)}</option>`).join('')}</select></label><div class="arrow">→</div><label>DESTINATION<select id="to"><option value="">Select a person</option>${people.map(n=>`<option value="${n.id}" ${state.to===n.id?'selected':''}>${esc(n.label)}</option>`).join('')}</select></label><button id="find-path" class="primary">FIND CONNECTION</button></div>${state.path.length?`<div class="path-result"><div class="path-meta">THE SHORTEST ROUTE <span>${state.path.length-1} degrees</span></div><div class="path-list">${state.path.map((id,i)=>{const n=state.nodes.find(x=>x.id===id);return `<div class="path-node" style="--node-color:${COLORS[n.type]}"><span>${String(i+1).padStart(2,'0')}</span><i></i><strong>${esc(n.label)}</strong><small>${n.type}</small></div>`}).join('')}</div></div>`:'<div class="empty-path"><span>✦</span><p>Your route will appear here.<br/>Try <b>Martin Scorsese</b> to <b>Robert De Niro</b>.</p></div>'}`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.activeView=b.dataset.view;render()}); const s=document.querySelector('#search');if(s){s.oninput=e=>{state.query=e.target.value; const q=state.query.toLowerCase();const found=state.nodes.find(n=>n.label.toLowerCase().includes(q));if(q&&found){state.selected=found;state.focus=found.id}render();document.querySelector('#search')?.focus();document.querySelector('#search')?.setSelectionRange(q.length,q.length)}} document.querySelector('#reset')?.addEventListener('click',()=>{state.selected=null;state.focus=null;state.query='';state.minYear=1970;render()});document.querySelector('#close')?.addEventListener('click',()=>{state.selected=null;state.focus=null;render()});document.querySelector('[data-focus]')?.addEventListener('click',e=>{state.focus=e.currentTarget.dataset.focus;render()});document.querySelector('#year')?.addEventListener('input',e=>{state.minYear=+e.target.value;render()});document.querySelectorAll('[data-year]').forEach(b=>b.onclick=()=>{state.minYear=+b.dataset.year;render()});document.querySelector('#from')?.addEventListener('change',e=>state.from=e.target.value);document.querySelector('#to')?.addEventListener('change',e=>state.to=e.target.value);document.querySelector('#find-path')?.addEventListener('click',findPath);window.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector('#search')?.focus()}}}
function findPath(){if(!state.from||!state.to||state.from===state.to)return;const q=[state.from],prev=new Map([[state.from,null]]);while(q.length){const cur=q.shift();if(cur===state.to)break;for(const e of state.edges){const next=e.source===cur?e.target:e.target===cur?e.source:null;if(next&&!prev.has(next)){prev.set(next,cur);q.push(next)}}}if(!prev.has(state.to)){state.path=[];render();return}const path=[];for(let x=state.to;x!==null;x=prev.get(x))path.unshift(x);state.path=path;render()}
function drawGraph(){const svg=document.querySelector('#graph');if(!svg)return;const box=svg.getBoundingClientRect(),w=box.width||900,h=box.height||600;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const base=filteredMovies();let visible;if(state.focus){visible=neighbors(state.focus)}else{const featured=[];const directors=new Set();for(const movie of base){if(!directors.has(movie.director)||featured.length<16){featured.push(movie);directors.add(movie.director)}if(featured.length>=24)break}visible=new Set(featured.flatMap(m=>['m:'+m.id,'d:'+slug(m.director),...m.cast.map(a=>'a:'+slug(a))]))}const nodes=state.nodes.filter(n=>visible.has(n.id));const edges=state.edges.filter(e=>visible.has(e.source)&&visible.has(e.target));const center={x:w/2,y:h/2};const pos=new Map();nodes.forEach((n,i)=>{const angle=i*2.399;const r=n.type==='film'?Math.min(w,h)*.27:Math.min(w,h)*.42;pos.set(n.id,{x:center.x+Math.cos(angle)*r*(.55+((i%7)/12)),y:center.y+Math.sin(angle)*r*(.55+((i%5)/10))})});if(state.focus)pos.set(state.focus,center);for(let pass=0;pass<18;pass++){nodes.forEach(n=>{const p=pos.get(n.id);let dx=(center.x-p.x)*.004,dy=(center.y-p.y)*.004;nodes.forEach(o=>{if(o===n)return;const q=pos.get(o.id),x=p.x-q.x,y=p.y-q.y,d=Math.max(28,Math.hypot(x,y)),f=1500/(d*d);dx+=x/d*f;dy+=y/d*f});edges.forEach(e=>{if(e.source===n.id||e.target===n.id){const other=pos.get(e.source===n.id?e.target:e.source),x=other.x-p.x,y=other.y-p.y,d=Math.max(1,Math.hypot(x,y));dx+=x/d*(d-95)*.008;dy+=y/d*(d-95)*.008}});p.x=Math.max(30,Math.min(w-30,p.x+dx));p.y=Math.max(30,Math.min(h-30,p.y+dy))})}
  svg.innerHTML=`<g class="edges">${edges.map(e=>{const a=pos.get(e.source),b=pos.get(e.target);return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="edge ${e.kind}"/>`}).join('')}</g><g class="nodes">${nodes.map(n=>{const p=pos.get(n.id),r=n.type==='film'?7:nodeDegree(n.id)>8?9:6;return `<g class="node ${state.selected?.id===n.id?'selected':''}" data-id="${n.id}" transform="translate(${p.x},${p.y})"><circle r="${r}" fill="${COLORS[n.type]}"/><text x="${r+7}" y="4">${esc(n.label.length>22?n.label.slice(0,21)+'…':n.label)}</text></g>`}).join('')}</g>`;svg.querySelectorAll('.node').forEach(el=>{el.onclick=()=>{state.selected=state.nodes.find(n=>n.id===el.dataset.id);render()};el.ondblclick=()=>{state.focus=el.dataset.id;state.selected=state.nodes.find(n=>n.id===el.dataset.id);render()}})}
init()
